services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
