name: backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [19.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install
        run: npm install -g pnpm
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm run build
      - name: lint
        run: pnpm lint
      - name: format
        run: pnpm format
